// src/components/Board.jsx
import { useCallback, useState } from 'react'
import Column from './Column.jsx'
import Well from './Well.jsx'
import Pack from '../models/Pack.js'
import Wells from '../models/Wells.js'
import Cards from '../data/cards.js'

export default function Board() {
  const [pack] = useState(() => new Pack(Cards))
  const [wells] = useState(() => new Wells())
  const [currentCard, setCurrentCard] = useState(null)
  const [origin, setOrigin] = useState(null)
  const [, setVersion] = useState(0)

  const onUpdate = useCallback(() => {
    setVersion((v) => v + 1)
  }, [])

  const onDragStartFrom = useCallback((card, from) => {
    setCurrentCard(card)
    setOrigin(from)
  }, [])

  const onDroppedCard = useCallback(
    (card, column) => {
      if (origin.isLadderHead(card)) {
        const cards = origin.getLadder()
        origin.removeLadder()
        pack.addLadderToColumn(cards, column.index)
      } else {
        origin.remove(card)
        column.add(card)
      }
      setCurrentCard(null)
      setOrigin(null)
      onUpdate()
    },
    [origin, pack, onUpdate]
  )

  const onDroppedCardInWell = useCallback(
    (card, well) => {
      origin.remove(card)
      well.add(card)
      setCurrentCard(null)
      setOrigin(null)
      onUpdate()
    },
    [origin, onUpdate]
  )

  return (
    <div className="flex">
      <div className="grid grid-cols-8 w-10/12">
        {pack.columns.map((column, index) => (
          <Column
            key={index}
            className="block mr-4"
            cardGroup={column}
            currentCard={currentCard}
            onDragStartFrom={onDragStartFrom}
            onDroppedCard={onDroppedCard}
            onUpdate={onUpdate}
          />
        ))}
      </div>
      <div className="w-2/12 pl-4 border-l border-gray-400">
        <h3 className="mb-4">Pozos</h3>
        <div className="grid grid-cols-2 gap-3">
          {wells.wells.map((well, index) => (
            <Well
              key={index}
              className="bg-gray-100 shadow-inner column--empty"
              cardGroup={well}
              currentCard={currentCard}
              onDragStartFrom={onDragStartFrom}
              onDroppedCard={onDroppedCardInWell}
              onUpdate={onUpdate}
            />
          ))}
        </div>
      </div>
    </div>
  )
}

// src/components/Board.vue
<template>
  <div class="flex">
    <div class="grid grid-cols-8 w-10/12">
      <CardGroup
        class="block mr-4"
        v-for="(cardGroup, index) in pack.columns"
        :key="index"
        :cardGroup="cardGroup"
        v-bind:onDroppedCard="onDroppedCard"
      />
    </div>
    <div class="w-2/12 pl-4 border-l border-gray-400">
      <h3 class="mb-4">Pozos</h3>
      <div class="grid grid-cols-2 gap-3">
        <Well
          class="bg-gray-100 shadow-inner column--empty"
          v-for="(well, index) in wells.wells"
          :key="index"
          :cardGroup="well"
          v-bind:onDroppedCard="onDroppedCardInWell"
        />
    </div>
    </div>
  </div>
</template>

<script>
import CardGroup from "./CardGroup.vue";
import Well from "./Well.vue";
import Cards from "../models/Cards.js";
import Pack from "../models/Pack.js";
import Wells from "../models/Wells.js";

const pack = new Pack(Cards);
const wells = new Wells();

export default {
  name: "Board",
  order: 1,
  components: {
    CardGroup,
    Well
  },
  data() {
    return {
      pack,
      wells
    };
  },
  methods: {
    onDroppedCard(cardId, destColumnIndex) {
      console.log("card dropped:", this.pack.findCardById(cardId));
      const card = this.pack.findCardById(cardId);
      if (card.cardGroup.isLadderHead(card)) {
        const cards = card.cardGroup.getLadder();
        console.log("card is ladder head, bring in the whole ladder!", cards);
        card.cardGroup.removeLadder();
        this.pack.addLadderToColumn(cards, destColumnIndex);
      } else {
        card.cardGroup.remove(card);
        this.pack.addCardToColumn(card, destColumnIndex);
      }
    },
    onDroppedCardInWell(cardId, wellIndex) {
      const card = this.pack.findCardById(cardId);
      card.cardGroup.remove(card);
      this.wells.addCardToWell(card, wellIndex);
    }
  }
};
</script>
