// src/components/Column.jsx
import Card from './Card.jsx'
import { useCardGroup } from '../hooks/useCardGroup.js'

export default function Column({
  cardGroup,
  currentCard,
  onDragStartFrom,
  onDroppedCard,
  onUpdate,
  className,
}) {
  const { isDraggable, onDragStart, onDragOver, onDragLeave, onDrop } =
    useCardGroup({
      cardGroup,
      currentCard,
      onDragStartFrom,
      onDroppedCard,
      onUpdate,
    })

  const columnClass =
    cardGroup.cards.length === 0
      ? [
          'border-gray-100',
          'bg-gray-100',
          'border',
          'rounded-lg',
          'shadow-inner',
          'column--empty',
          cardGroup.willReceive && 'bg-green-100',
          className,
        ]
          .filter(Boolean)
          .join(' ')
      : [className].filter(Boolean).join(' ')

  return (
    <div
      onDragOver={onDragOver}
      onDragLeave={onDragLeave}
      onDrop={onDrop}
      className={columnClass}
    >
      {cardGroup.cards.map((card) => (
        <Card
          key={card.id}
          card={card}
          onDragStart={onDragStart}
          draggable={isDraggable(card)}
        />
      ))}
    </div>
  )
}

// src/components/Column.vue
<template>
  <div
    v-on:dragover="onDragOver"
    v-on:dragleave="onDragLeave"
    v-on:drop="onDrop"
    v-bind:class="columnClass"
  >
    <Card
      v-for="card in cardGroup.cards"
      :key="card.id"
      :card="card"
      v-bind:dragStart="onDragStart"
      :draggable="isDraggable(card)"
    >
    </Card>
  </div>
</template>

<script>
import Column from "../models/Column.js";
import CardClass from "../models/Card.js";
import cardGroup from "../mixins/cardGroup.js";
import Card from "./Card.vue";

export default {
  name: "Column",
  components: {
    Card
  },
  mixins: [cardGroup],
  props: {
    cardGroup: Column,
    currentCard: CardClass,
    onDragStartFrom: Function,
    onDroppedCard: Function
  },
  computed: {
    columnClass() {
      return this.cardGroup.cards.length === 0
        ? [
            "border-gray-100",
            "bg-gray-100",
            "border",
            "rounded-lg",
            "shadow-inner",
            "column--empty",
            this.cardGroup.willReceive && "bg-green-100"
          ]
        : [];
    }
  }
};
</script>
