// src/components/Well.jsx
import Card from './Card.jsx'
import { useCardGroup } from '../hooks/useCardGroup.js'

export default function Well({
  cardGroup,
  currentCard,
  onDragStartFrom,
  onDroppedCard,
  onUpdate,
  className,
}) {
  const { isDraggable, onDragStart, onDragOver, onDragLeave, onDrop } =
    useCardGroup({
      cardGroup,
      currentCard,
      onDragStartFrom,
      onDroppedCard,
      onUpdate,
    })

  const wellClass = [
    'relative',
    cardGroup.willReceive && 'bg-green-100',
    className,
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div
      onDragOver={onDragOver}
      onDragLeave={onDragLeave}
      onDrop={onDrop}
      className={wellClass}
    >
      {cardGroup.cards.map((card) => (
        <Card
          key={card.id}
          className="card--in-well"
          card={card}
          onDragStart={onDragStart}
          draggable={isDraggable(card)}
        />
      ))}
    </div>
  )
}

// src/components/Well.vue
<template>
  <div
    v-on:dragover="onDragOver"
    v-on:dragleave="onDragLeave"
    v-on:drop="onDrop"
    class="relative"
    v-bind:class="{ 'bg-green-100': cardGroup.willReceive }"
  >
    <Card
      class="card--in-well"
      v-for="card in cardGroup.cards"
      :key="card.id"
      :card="card"
      v-bind:dragStart="onDragStart"
      :draggable="isDraggable(card)"
    >
    </Card>
  </div>
</template>

<script>
import Well from "../models/Well.js";
import CardClass from "../models/Card.js";
import cardGroup from "../mixins/cardGroup.js";
import Card from "./Card.vue";

export default {
  name: "Well",
  components: {
    Card
  },
  mixins: [cardGroup],
  props: {
    cardGroup: Well,
    currentCard: CardClass,
    onDragStartFrom: Function,
    onDroppedCard: Function
  }
};
</script>
